/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bdc8cb",
        "surface-dim": "#dadada",
        "on-primary-fixed": "#001f25",
        "on-error-container": "#93000a",
        "tertiary": "#a91929",
        "tertiary-fixed": "#ffdad8",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-container": "#586377",
        "secondary-fixed": "#d8e3fa",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#410007",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-container": "#cc353e",
        "inverse-primary": "#7ad4e5",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#7ad4e5",
        "primary-container": "#007a8a",
        "outline": "#6e797b",
        "secondary": "#545f72",
        "on-surface-variant": "#3e494b",
        "surface-tint": "#006876",
        "secondary-container": "#d5e0f7",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#f9f9f9",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#92001b",
        "secondary-fixed-dim": "#bcc7dd",
        "on-primary-fixed-variant": "#004e59",
        "surface-bright": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "on-secondary-fixed": "#111c2c",
        "tertiary-fixed-dim": "#ffb3b0",
        "on-tertiary-container": "#ffefee",
        "primary-fixed": "#a0efff",
        "surface-container": "#eeeeee",
        "inverse-surface": "#2f3131",
        "on-error": "#ffffff",
        "background": "#f9f9f9",
        "primary": "#005f6c",
        "on-surface": "#1a1c1c",
        "on-primary-container": "#daf8ff",
        "on-background": "#1a1c1c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
}

